### ISSUE TITLE
New Hackathon request!!!

### ISSUE THREAD

**Issue by AnandChowdhary** [abranhe/hackathon-badges#7]
**Required***
  
_name_: BharatHacks
_website_: https://bharathacks.github.io

**Not required**

Official logo picture url: https://bharathacks.github.io/assets/icons/apple-touch-icon.png
Background image: 
Cover photo: https://bharathacks.github.io/assets/images/poster1.png

Note: We're going to do another BharatHacks coming January!

**Comment by abranhe** [comment]
Cool, we are happy to add it as soon as possible!

**Comment by abranhe** [comment]
We are now supporting BharatHacks 😃

[![BharatHacks](https://hackathon.badge.pw/bharathacks)](https://bharathacks.com/)

```md
[![BharatHacks](https://hackathon.badge.pw/bharathacks)](https://bharathacks.com/)
```
